language: generic
sudo: required
services:
- docker
before_script:
- cd backend
script:
- npm install
- npm test
after_success:
- cd ..
- docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
- heroku update
- heroku container:push web --app typescript-project
- heroku container:release web --app typescript-project
