language: generic
sudo: required
services:
- docker
script:
- cd backend
- npm install
- npm test
- cd ..
after_success:
- docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
- heroku update
- heroku container:push web --app typescript-project
- heroku container:release web --app typescript-project
