language: generic
sudo: required
services:
- docker
before_script:
- docker-compose build
after_success:
  # for local testing, needs to be set on travis, too:
  # export HEROKU_TOKEN=$(heroku auth:token)
- docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
- docker build -t registry.heroku.com/typescript-project/web -f Dockerfile .
- docker push registry.heroku.com/typescript-project/web
- heroku run --app typescript-project
