language: generic
sudo: required
services:
- docker
before_script:
- echo "Hello"
after_success:
  # for local testing, needs to be set on travis, too:
  # export HEROKU_TOKEN=$(heroku auth:token)
- . ./deploy-to-dev.sh
