version: '3.3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run start
    ports:
      - 4200:4200
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 5000:80
    command: npm run start:dev
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres-dev-db
    environment:
      PORT: 80

  postgres-dev-db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vantaa_pwa

  admin:
    image: adminer
    ports:
      - 8080:8080