version: '3.3'

services:

  typescript_project:
    image: typescript_project
    ports:
      - 3000:3000
    command: bash -c 'npm install && npm start'
    depends_on:
      - postgres-dev-db
    environment:
      PORT: 3000

  postgres-dev-db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vantaa_pwa

  admin:
    image: adminer
    ports:
      - 8080:8080